# Generated by Django 5.1.3 on 2024-11-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'To-Do Item', 'verbose_name_plural': 'To-Do Items'},
        ),
        migrations.AddField(
            model_name='todo',
            name='image',
            field=models.ImageField(default='img/default-image.jpg', upload_to='todo_images'),
        ),
        migrations.AddField(
            model_name='todo',
            name='video',
            field=models.FileField(default=0, upload_to='todo_videos'),
            preserve_default=False,
        ),
    ]
